### ISSUE TITLE
There are some problems when running `yarn start`

### ISSUE THREAD

**Issue by wafeishushu** [ziad-saab/ethdenver-2023-metamask-snaps-workshop#1]
I'm trying to create a new snap, but I'm having problems with yarn start.
Could you please tell me what's going on? Thanks!
OS: Mac
Node: 18.3.0

```bash
$ yarn start
➤ YN0000: [site]: Process started
➤ YN0000: [snap]: Process started
➤ YN0000: [snap]: - Checking the input file.
➤ YN0000: [snap]: - Starting the development server.
➤ YN0000: [snap]: ℹ The server is listening on http://localhost:8080.
➤ YN0000: [snap]: - Building the snap bundle.
➤ YN0000: [snap]: /Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/@metamask/snaps-cli/dist/cjs/webpack/plugins.js:215
➤ YN0000: [snap]:             if ((0, _module.isBuiltin)(baseRequest) && !this.options.ignore?.includes(baseRequest)) {
➤ YN0000: [snap]:                                       ^
➤ YN0000: [snap]: 
➤ YN0000: [snap]: TypeError: (0 , _module.isBuiltin) is not a function
➤ YN0000: [snap]:     at /Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/@metamask/snaps-cli/dist/cjs/webpack/plugins.js:215:39
➤ YN0000: [snap]:     at Hook.eval [as callAsync] (eval at create (/Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:37:1)
➤ YN0000: [snap]:     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/tapable/lib/Hook.js:18:14)
➤ YN0000: [snap]:     at Resolver.doResolve (/Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/enhanced-resolve/lib/Resolver.js:516:16)
➤ YN0000: [snap]:     at /Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:76:17
➤ YN0000: [snap]:     at /Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:145:13
➤ YN0000: [snap]:     at /Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/enhanced-resolve/lib/forEachBail.js:39:13
➤ YN0000: [snap]:     at onJson (/Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:130:6)
➤ YN0000: [snap]:     at /Users/wafei/code/ziad-saab/transaction-insights-snaps-workshop/node_modules/enhanced-resolve/lib/DescriptionFileUtils.js:83:7
➤ YN0000: [snap]:     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by ziad-saab** [comment]
Please make sure you are using a Node version of at least v16.17.0
